{
    "openapi": "3.0.0",
    "info": {
        "title": "Raro Mailer",
        "description": "API to make easy automated employee onboarding for human resources teams. Made with TypeORM and MariaDB.",
        "license": {
            "name": "MIT",
            "url": "https://spdx.org/licenses/MIT.html"
          },
        "contact": {
            "email": "rkbuarque@gmail.com"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:3333",
            "description": "Development server"
        }
    ],
    "paths": {
        "/users": {
            "get": {
                "summary": "Get all users",
                "description": "This route is responsible to get all users",
                "tags": [
                    "users"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/User"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "summary": "Sign Up",
                "description": "This route is responsible to Sign Up users",
                "tags": [
                    "users"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/User"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "id": 1,
                                        "firstName": "Bruce",
                                        "lasName": "Wayne",
                                        "position": "Human Resources",
                                        "phoneNumber": "7777777",
                                        "email": "wayne.bruce@iam.batman.com",
                                        "password": "1234secret"
                                    }
                                }
                            } 
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/User"
                                }
                            }
                        }
                    }
                }
            }    
        },
        "/users/{id}": {
            "get": {
                "summary": "Get a user by ID",
                "description": "This route is responsible to get a user by ID",
                "tags": [
                    "users"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "User data by ID",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/User"
                                }
                            }
                        }
                    }
                } 
            },
            "patch": {
                "summary": "Update a user",
                "description": "This route is responsible to update a user",
                "tags": [
                    "users"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "update user data by ID",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/User"
                                }
                            }
                        }
                    }
                } 
            },
            "delete": {
                "summary": "Delete a user",
                "description": "This route is responsible to delete a user",
                "tags": [
                    "users"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "delete user data by ID",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/User"
                                }
                            }
                        }
                    }
                } 
            }
        },
        "/users/authenticate": {
            "post": {
                "summary": "Authenticate a user",
                "description": "This route is responsible to authenticate a user",
                "tags": [
                    "users"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/User"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "id": 1,
                                        "firstName": "Bruce",
                                        "lasName": "Wayne",
                                        "position": "Human Resources",
                                        "phoneNumber": "7777777",
                                        "email": "wayne.bruce@iam.batman.com"
                                    }
                                }
                            } 
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/User"
                                }
                            }
                        }
                    }
                }
            } 
        },
        "/actors": {
            "get": {
                "summary": "Get all actors",
                "description": "This route is responsible to get all actors",
                "tags": [
                    "actors"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/Actor"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "summary": "Create an actor",
                "description": "This route is responsible to create an actor",
                "tags": [
                    "actors"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Actor"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "id": 2,
                                        "firstName": "Bruce",
                                        "lasName": "Wayne",
                                        "position": "Human Resources",
                                        "phoneNumber": "7777777",
                                        "email": "wayne.bruce@iam.batman.com",
                                        "department": "Gotham city justice system"
                                    }
                                }
                            } 
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/Actor"
                                }
                            }
                        }
                    }
                }
            }        
        },
        "/actors/{id}": {
            "get": {
                "summary": "Get an actor by ID",
                "description": "This route is responsible to get an actor by ID",
                "tags": [
                    "actors"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Actor data by ID",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/Actor"
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "summary": "Update an actor",
                "description": "This route is responsible to update an actor",
                "tags": [
                    "actors"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "update actor data by ID",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/Actor"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Delete an actor",
                "description": "This route is responsible to delete an actor",
                "tags": [
                    "actors"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "delete actor data by ID",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/Actor"
                                }
                            }
                        }
                    }
                }
            }    
        },
        "/employees": {
            "get": {
                "summary": "Get all employees",
                "description": "This route is responsible to get all employees",
                "tags": [
                    "employees"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/Employee"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "summary": "Create an employee",
                "description": "This route is responsible to create an employee",
                "tags": [
                    "employees"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Employee"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "id": 3,
                                        "firstName": "Bruce",
                                        "lasName": "Wayne",
                                        "position": "Human Resources",
                                        "phoneNumber": "7777777",
                                        "email": "wayne.bruce@iam.batman.com",
                                        "department": "Gotham city justice system"
                                    }
                                }
                            } 
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/Employee"
                                }
                            }
                        }
                    }
                }
            }        
        },
        "/employees/{id}": {
            "get": {
                "summary": "Get an employee by ID",
                "description": "This route is responsible to get an employee by ID",
                "tags": [
                    "employees"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Employee name by ID",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/Employee"
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "summary": "Update an employee",
                "description": "This route is responsible to update an employee",
                "tags": [
                    "employees"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "update employee data by ID",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/Employee"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Delete an employee",
                "description": "This route is responsible to delete an employee",
                "tags": [
                    "employees"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "delete employee data by ID",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/Employee"
                                }
                            }
                        }
                    }
                }
            }    
        },
        "/action-templates": {
            "get": {
                "summary": "Get all templates",
                "description": "This route is responsible to get all templates",
                "tags": [
                    "action templates"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/ActionTemplate"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "summary": "Create a template",
                "description": "This route is responsible to create a template",
                "tags": [
                    "action templates"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/ActionTemplate"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "name": "boas vindas",
                                        "subject": "boas vindas",
                                        "body": "boas vindas"
                                    }
                                }
                            } 
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/ActionTemplate"
                                }
                            }
                        }
                    }
                }
            }        
        },
        "/action-templates/{id}": {
            "get": {
                "summary": "Get a template by ID",
                "description": "This route is responsible to get a template by ID",
                "tags": [
                    "action templates"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Action template data by ID",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/ActionTemplate"
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "summary": "Update a template",
                "description": "This route is responsible to update a template",
                "tags": [
                    "action templates"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "update action template data by ID",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/ActionTemplate"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Delete a template",
                "description": "This route is responsible to delete a template",
                "tags": [
                    "action templates"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "delete action template data by ID",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/ActionTemplate"
                                }
                            }
                        }
                    }
                }
            }    
        },
        "/schemes": {
            "get": {
                "summary": "Get all schemes",
                "description": "This route is responsible to get all schemes",
                "tags": [
                    "schemes"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/Scheme"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "summary": "Create a scheme",
                "description": "This route is responsible to create a scheme",
                "tags": [
                    "schemes"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Scheme"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "name": "teste"
                                    }
                                }
                            } 
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/Scheme"
                                }
                            }
                        }
                    }
                }
            }        
        },
        "/schemes/{id}": {
            "get": {
                "summary": "Get a scheme by ID",
                "description": "This route is responsible to get a scheme by ID",
                "tags": [
                    "schemes"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Scheme data by ID",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/Scheme"
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "summary": "Update a scheme",
                "description": "This route is responsible to update a scheme",
                "tags": [
                    "schemes"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "update scheme data by ID",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/Scheme"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Delete a scheme",
                "description": "This route is responsible to delete a scheme",
                "tags": [
                    "schemes"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "delete scheme data by ID",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/Scheme"
                                }
                            }
                        }
                    }
                }
            }    
        },
        "/bundles": {
            "get": {
                "summary": "Get all bundles",
                "description": "This route is responsible to get all bundles",
                "tags": [
                    "bundles"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/Bundle"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "summary": "Create a bundle",
                "description": "This route is responsible to create a bundle",
                "tags": [
                    "bundles"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Bundle"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "id": 1
                                    }
                                }
                            } 
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/Bundle"
                                }
                            }
                        }
                    }
                }
            }        
        },
        "/bundles/{id}": {
            "get": {
                "summary": "Get a bundle by ID",
                "description": "This route is responsible to get a bundle by ID",
                "tags": [
                    "bundles"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "bundle data by ID",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/Bundle"
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "summary": "Update a bundle",
                "description": "This route is responsible to update a bundle",
                "tags": [
                    "bundles"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "update bundle data by ID",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/Bundle"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Delete a bundle",
                "description": "This route is responsible to delete a bundle",
                "tags": [
                    "bundles"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "delete bundle data by ID",
                        "required": true
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "$ref": "#/components/schemas/Bundle"
                                }
                            }
                        }
                    }
                }
            }    
        }
        
            
    },
    "components": {
        "schemas": {
            "User": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "firstName": {
                        "type": "string"
                    },
                    "lastName": {
                        "type": "string"
                    },
                    "position": {
                        "type": "string"
                    },
                    "phoneNumber": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    }
                }
            },
            "Actor": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "firstName": {
                        "type": "string"
                    },
                    "lastName": {
                        "type": "string"
                    },
                    "position": {
                        "type": "string"
                    },
                    "phoneNumber": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "department": {
                        "type": "string"
                    }
                }
            },
            "Employee": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "firstName": {
                        "type": "string"
                    },
                    "lastName": {
                        "type": "string"
                    },
                    "position": {
                        "type": "string"
                    },
                    "phoneNumber": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "department": {
                        "type": "string"
                    }
                }
            },
            "ActionTemplate": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "name": {
                        "type": "string"
                    },
                    "subject": {
                        "type": "string"
                    },
                    "body": {
                        "type": "string"
                    }
                }
            },
            "Scheme": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "name": {
                        "type": "string"
                    }
                }
            },
            "Bundle":{
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    }
                }
            }
        },
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}